algo_para:
- 0.5
- 0.5
- 0.001
batch_size: 50
clip_grad: 10
learning_rate: 0.05
learning_rate_decay: 0.9998
local_test: true
log_file: true
lr_scheduler: 0
no_log_console: true
no_tqdm: true
num_epochs: 5
num_rounds: 500
proportion: 1.0
train_holdout: 0.2
weight_decay: 1e-3
